# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import manager.validators


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='name',
            field=models.CharField(max_length=100, validators=[manager.validators.validate_transaction_name]),
        ),
    ]
