# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import manager.validators


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20170408_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, validators=[manager.validators.validate_category_name]),
        ),
    ]
